import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PhoneProvider } from "./context/phone";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PhoneProvider>
          {children}
        </PhoneProvider>
      </body>
    </html>
  );
}
